---
```
This configuration file defines an environment.
```
environment:
  name: training
  description: "Training day.  Get some!"
  aws:
    cloudformation:
      regions:
        primary: us-east-1
        secondary: us-west-2
        dr: us-west-1
      profiles:
        primary:
          size: t2.micro
          min: 2
          max: 2
        secondary:
          size: t2.micro
          min: 1
          max: 1
        dr:
          size: t2.micro
          min: 1
          max: 1
