---
# This configuration file defines an environment.
environment:
  name: training
  description: "Training day.  Get some!"
  chef:
    version: 0.1.0
  aws:
    cloudformation:
      inf_version: 1.1.3
      zones:
        elb: us-east-1d
        public: us-east-1d
        private: us-east-1d
      regions: 
        primary: us-east-1
